### PR TITLE
Add option to sort results by package name

### PR DESCRIPTION
**Pull request by dsoares**

### CODE REVIEW

**Comment by dsoares** [comment]
Hi,
Please review the code with the new commit 1bb7d6c.

**Comment by genevera** [comment]
.... But why?:(

**Comment by victorgarric** [comment]
Hello,
I'm sorry but I've made many changes after a while and your proposal/commit was not working with the other changes. However, it was a great improvement. So, if you wanna make it work with the latest version, I would merge it with pleasure.
Sorry again. 

Regards,

**Comment by dsoares** [comment]
Submitted a new PR victorgarric/pip_search#17

**Pull request closed without merging**
